### POST request to create a new user
POST http://localhost:5001/api/auth/signup
Content-Type: application/json

{
    "fullName": "Stream User-Agent: Test",
    "email": "test2@iway.com",
    "password": "securepassword123"
}

###