### POST request to onboard a user
POST http://localhost:5001/api/auth/onboarding
Content-Type: application/json

{
    "fullName": "Test User5",
    "email": "test5@iway.com",
    "bio": "Just a regular user5",
    "nativeLanguage": "Hindi",
    "learningLanguage": "English",
    "location": "UK"
}

###