### POST request to create a new user
POST http://localhost:5001/api/auth/signup
Content-Type: application/json

{
    "fullName": "Mr. Strange",
    "email": "test@iway.com",
    "password": "securepassword123"
}

###